settings:
  docker:
    parent_image: 763104351884.dkr.ecr.us-east-2.amazonaws.com/pytorch-training:2.2.0-gpu-py310-cu121-ubuntu20.04-sagemaker
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  is_dummy: true # Change this to 'false' to run the evaluation on the full dataset.
