settings:
  docker:
    parent_image: 992382797823.dkr.ecr.us-east-2.amazonaws.com/zenml-rlwlcs:latest
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  artifact_names:
    - raw_documents
    - cleaned_documents
    - instruct_datasets
    - preference_datasets
