settings:
  docker:
    parent_image: 763104351884.dkr.ecr.us-east-2.amazonaws.com/pytorch-training:2.2.0-gpu-py310-cu121-ubuntu20.04-sagemaker
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  finetuning_type: sft
  num_train_epochs: 3
  per_device_train_batch_size: 2
  learning_rate: 3e-4
  dataset_huggingface_workspace: mlabonne
  is_dummy: true # Change this to 'false' to run the training with the full dataset and epochs.
